### ISSUE TITLE
Crash in MockSensorTest.DeletedListener in docker container

### ISSUE THREAD

**Issue by jeffkilpatrick** [jeffkilpatrick/thermocouple#27]
# Repro
1. Ensure you're working in a branch with docker support
2. docker run thermocouple-build

## Expected
* Everything builds and tests succeed

## Actual
* Everything builds but tests crash.

Sample output:

> [==========] Running 10 tests from 2 test cases.
> [----------] Global test environment set-up.
> [----------] 5 tests from MockSensorTest
> [ RUN      ] MockSensorTest.Interval
> [       OK ] MockSensorTest.Interval (61 ms)
> [ RUN      ] MockSensorTest.MultiValue
> [       OK ] MockSensorTest.MultiValue (61 ms)
> [ RUN      ] MockSensorTest.Delta
> [       OK ] MockSensorTest.Delta (23 ms)
> [ RUN      ] MockSensorTest.Pause
> [       OK ] MockSensorTest.Pause (45 ms)
> [ RUN      ] MockSensorTest.DeletedListener
> ./build.sh: line 92:   361 Segmentation fault      "$builddir/unittest/unittest"

**Comment by jeffkilpatrick** [comment]
### Root Cause
`AbstractSensor::Notify` attempts to optimize its subscriptions map by proactively deleting any subscriptions it finds without valid listeners. It does so by calling `std::unordered_map::erase` while iterating over that map. I interpret the the comments on [this page](https://en.cppreference.com/w/cpp/container/unordered_map/erase) to indicate this is valid, but libstdc++ does not. Somebody is wrong, but it doesn't really matter: this optimization is not necessary for correctness and is exceedingly unlikely to make any performance difference, so I'll just delete it.

### Analysis Notes
The subscription appears to be bogus at time of crash:
> (gdb) f 2
> #2  0x00007f699b065ccd in Subscription::GetListener (this=0x15a5c35ee0e3c1c4) at /opt/thermocouple/src/private/Subscription.cpp:28
> 28	    return m_listener;
> (gdb) p this
> $1 = (const Subscription * const) 0x15a5c35ee0e3c1c4
> (gdb) p *this
> Cannot access memory at address 0x15a5c35ee0e3c1c4
> (gdb) p this->m_status
> Cannot access memory at address 0x15a5c35ee0e3c1dc

The sensor holding the subscription seems okay:
(gdb) f 3

> #3  0x00007f699b05761f in AbstractSensor::Notify (this=0x55eddc089cb8, value=35, time=...) at /opt/thermocouple/src/private/AbstractSensor.cpp:91
> 91	        if (sub->GetListener().expired()) {
> ...
> (gdb) p this->m_identifier
> $6 = "mock"

In fact, the sensor has somehow forgotten about the subscription for listener1 (which was registered with subId = 1; only subscription 2 remains):

> (gdb) p this->m_subscriptions
> $2 = std::unordered_map with 1 element = {[2] = std::shared_ptr<Subscription> (use count 1, weak count 0) = {get() = 0x5654b18504a0}}
> 

`printf` debugging points to the `AbstractSensor::Notify` loop coming across the subscription without a valid listener and proactively deleting it. We subsequently crash when accessing the next element. Deleting this element [is supposed to be valid in C++14](https://en.cppreference.com/w/cpp/container/unordered_map/erase), but appears to not be in whatever C++ lib we're linking against.

### Stack trace of crash
> #0  0x00007f699b0636c0 in std::__weak_ptr<IListener, (__gnu_cxx::_Lock_policy)2>::__weak_ptr (this=0x7f69999dbcd0) at /usr/include/c++/7/bits/shared_ptr_base.h:1607
> #1  0x00007f699b06370b in std::weak_ptr<IListener>::weak_ptr (this=0x7f69999dbcd0) at /usr/include/c++/7/bits/shared_ptr.h:540
> #2  0x00007f699b065ccd in Subscription::GetListener (this=0x15a5c35ee0e3c1c4) at /opt/thermocouple/src/private/Subscription.cpp:28
> #3  0x00007f699b05761f in AbstractSensor::Notify (this=0x55eddc089cb8, value=35, time=...) at /opt/thermocouple/src/private/AbstractSensor.cpp:91
> #4  0x00007f699b05a2d5 in MockSensor::PollAndNotify (this=0x55eddc089cb0) at /opt/thermocouple/src/private/MockSensor.cpp:33
> #5  0x00007f699b06440d in SensorPoller::RunLoop (this=0x55eddc089c00) at /opt/thermocouple/src/private/SensorPoller.cpp:59
> #6  0x00007f699b064211 in SensorPoller::<lambda()>::operator()(void) const (__closure=0x55eddc089058) at /opt/thermocouple/src/private/SensorPoller.cpp:34
> #7  0x00007f699b06467f in std::__invoke_impl<void, SensorPoller::Start()::<lambda()> >(std::__invoke_other, SensorPoller::<lambda()> &&) (__f=...)
>     at /usr/include/c++/7/bits/invoke.h:60
> #8  0x00007f699b0644c4 in std::__invoke<SensorPoller::Start()::<lambda()> >(SensorPoller::<lambda()> &&) (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
> #9  0x00007f699b0648aa in std::thread::_Invoker<std::tuple<SensorPoller::Start()::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x55eddc089058)
>     at /usr/include/c++/7/thread:234
> #10 0x00007f699b06487b in std::thread::_Invoker<std::tuple<SensorPoller::Start()::<lambda()> > >::operator()(void) (this=0x55eddc089058)
>     at /usr/include/c++/7/thread:243
> #11 0x00007f699b06485a in std::thread::_State_impl<std::thread::_Invoker<std::tuple<SensorPoller::Start()::<lambda()> > > >::_M_run(void) (this=0x55eddc089050)
>     at /usr/include/c++/7/thread:186
> #12 0x00007f699ab1466f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> #13 0x00007f699ade76db in start_thread (arg=0x7f69999dc700) at pthread_create.c:463
> #14 0x00007f699a56f88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
>
